# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=3)),
                ('licenses_available', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('notes', models.TextField()),
                ('virtual', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField()),
                ('created', models.DateTimeField()),
                ('online_date', models.DateField()),
                ('server_id', models.CharField(max_length=6)),
                ('use', models.CharField(choices=[('PROD', 'Prod'), ('DEV', 'Dev')], default='DEV', max_length=4)),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.OperatingSystem')),
            ],
        ),
    ]
