# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
