# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingsystem',
            name='version',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='operatingsystem',
            unique_together=set([('name', 'version')]),
        ),
    ]
