# Generated by Django 3.0.4 on 2020-03-29 14:00

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='middle name')),
                ('last_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Last name')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender')),
                ('national_id', models.CharField(max_length=50, verbose_name='National id')),
                ('national_id_type', models.IntegerField(choices=[(1, 'National Id'), (2, 'Drivers License'), (3, 'Passport'), (4, 'Other')], default='NATIONAL_ID', verbose_name='National id type')),
                ('country_for_id', django_countries.fields.CountryField(max_length=2, verbose_name='Country for id')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('blood_type', models.CharField(blank=True, max_length=4, null=True, verbose_name='Blood type')),
                ('religion', models.CharField(blank=True, max_length=60, null=True, verbose_name='Religion')),
                ('document', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
