from abc import ABC, abstractmethod


class TemplateGenerator(ABC):

    @abstractmethod
    def generate(self, template_data: dict):
        """Generates conten based on a Jinja template"""


class TemplateDataParser(ABC):
    """
    This class will take the dictionary generated by django_test_tools.app_manager.AppDataParser
    and formatted in a way the template can use it.
    """

    @abstractmethod
    def parse_data(self, app_data: dict) -> dict:
        """Parses dictionary to create data for template"""
